### ISSUE TITLE
input file contain multiple molecules

### ISSUE THREAD

**Issue by fangxintao** [AlgoMole/MolCRAFT#13]
python sample_for_pocket.py ${PDB_PATH} ${SDF_PATH}

The input file（SDF file） can contain two or more small molecules？

**Comment by qky18** [comment]
Hi, in that case, there might be some undefined behavior in clipping the 10A region around the ligand to obtain the binding site, though no errors will be thrown.
If the input SDF contains several molecules within roughly the same binding site, I suspect it would be just fine. But if they are scattered into multiple (and often very distant) sites, it might not yield satisfactory results since the clipped pocket would be nasty.
